### ISSUE TITLE
move umami to secrets

### ISSUE THREAD

**Issue by dmksnnk** [dmksnnk/blog#2]
Here's what LLM says:

Yes! You can use GitHub Secrets to conditionally inject tracking. Here's how to set it up:

1. Add GitHub Secret
Go to your repository → Settings → Secrets and variables → Actions → New repository secret:

Name: ANALYTICS_WEBSITE_ID
Value: <your value>
2. Update your Hugo template
```
{{ if and (not hugo.IsServer) .Site.Params.analyticsId }}
<script defer src="https://analytics.getpid.dev/definitely-not-umami.js" data-website-id="{{ .Site.Params.analyticsId }}"></script>
{{ end }}
```
3. Update your GitHub Actions workflow
```
# ...existing code...
      - name: Build hugo
        run: |
          hugo build --minify
        env:
          HUGO_PARAMS_ANALYTICSID: ${{ secrets.ANALYTICS_WEBSITE_ID }}
# ...existing code...
```

5. Alternative: Use Hugo's built-in environment variables
```
{{ if and (not hugo.IsServer) (getenv "HUGO_PARAMS_ANALYTICSID") }}
<script defer src="https://analytics.getpid.dev/definitely-not-umami.js" data-website-id="{{ getenv "HUGO_PARAMS_ANALYTICSID" }}"></script>
{{ end }}
```

This way:

Local development: No tracking (secret not set)
GitHub Actions: Tracking enabled with secret
Public repo: Secret value is hidden, code is clean
The secret won't be exposed in your public repository, and you can easily disable tracking by removing the secret.
